### PR TITLE
adding colab file

### PR DESCRIPTION
**Pull request by Saimmohd**
This is a request to add my collab notebook to main

### CODE REVIEW

**Review by sparsh-ai — CHANGES_REQUESTED** [review]
Great!. Only one small change - instead of MS_Colab.ipynb, please name it MS-Colab.ipynb

**Review by sparsh-ai — CHANGES_REQUESTED** [review]
Also, the path of this notebook seems incorrect.

**Comment by Saimmohd** [comment]
@sparsh-ai  Will change the file name. I ll check the path again as well

**Comment by Manish22332** [comment]
the colab notebook should be in tests/colab/MS-colab.ipnyb, currently it's in the root directory

**Comment by Saimmohd** [comment]
I think I have added the file in the correct folder now. Could you please check ?

**Review by sparsh-ai — APPROVED** [review]
LGTM!

**Pull request merged**
